# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
Guest.destroy_all

guests = [
  { full_name: 'Uliana Mishina' },
  { full_name: 'Evelina Obretetskaya' },
  { full_name: 'Tatiana Obretetskaya' },
  { full_name: 'Matthew Rapp' },
  { full_name: 'Jennifer Montgomery' },
  { full_name: 'Benjamin Rapp' },
  { full_name: 'Oliver Rapp' },
  { full_name: 'Tatiana Mishina' },
  { full_name: 'Lena Mishina' },
  { full_name: 'Jessica Lewis' },
  { full_name: 'Aleksandr Oleinikov' },
  { full_name: 'Polina Oleinikova' },
  { full_name: 'Arseniy Oleinkov' },
  { full_name: 'Irina Moiseeva' },
  { full_name: 'Harry James' },
  { full_name: 'Tobias Stroud-Turp' },
  { full_name: 'Jack Vitrotti' },
  { full_name: 'Jimmy Daniel' },
  { full_name: 'Ruby Beeden' },
  { full_name: 'Finn Munkenbeck' },
  { full_name: 'Ben Lewthwaite' },
  { full_name: 'Imran Seth' },
  { full_name: 'Justin Augustus' },
  { full_name: 'Kent Zeigler' },
  { full_name: 'Sergei Litvinyenko' },
  { full_name: 'Tanya Chebotaryova' },
  { full_name: 'Anna Ivanova Thompson' },
  { full_name: 'Ksenia Volkova' },
  { full_name: 'Evegenia Kirsanova' },
  { full_name: 'Shameer Khawar' },
  { full_name: 'Harry Collins' },
  { full_name: 'Ares Agourdes' },
  { full_name: 'Hadrien Utenhoven' },
  { full_name: 'Thomas Bentham' },
  { full_name: 'Matthew Williams' },
  { full_name: 'Siwaj Na Songkhla' },
  { full_name: 'Ryan Evans' },
  { full_name: 'Hannah White' },
  { full_name: 'Anne Pearson Smith' },
  { full_name: 'Lucy Weaver' },
  { full_name: 'Molly Patton' },
  { full_name: 'Miles Patton' },
  { full_name: 'Valentina Lupi' },
  { full_name: 'Naomi Ingram' },
  { full_name: 'Stefanie Rangel' },
  { full_name: 'Annabel Buxton' },
  { full_name: 'Rosie Mckenzie' },
  { full_name: 'Ellen McCreadie' },
  { full_name: 'Philip Tanner' },
  { full_name: 'Steven Rapp' },
  { full_name: 'Thomas Rapp' },
  { full_name: 'Emily Rapp Arias' },
  { full_name: 'Andrew Rapp' },
  { full_name: 'Sam Rapp' },
  { full_name: 'Nicholas Rapp' },
  { full_name: 'Sean Rapp' },
  { full_name: 'Tim Meserve' },
  { full_name: 'Nick Meserve' },
  { full_name: 'Eleanor Farraguna' },
  { full_name: 'Jeannette Terry' },
  { full_name: 'Maxwell Wellman' },
  { full_name: 'Natalie Werner' },
  { full_name: 'Eric Montgomery' },
  { full_name: 'Danielle Sorensen' },
  { full_name: ' Ksenia Alpatova' },
  { full_name: 'Lyosha Alpatov' },
  { full_name: 'Lena Oleinikova' },
  { full_name: 'Anya Moiseeva' },
  { full_name: 'Carolina Pestana Vieira' },
  { full_name: 'Jessica Gutaj' },
  { full_name: 'Sol' },
  { full_name: 'Madison Thomas' },
  { full_name: 'Olga Litvinyenko' },
  { full_name: 'Bea Chavdarova' },
  { full_name: 'Jon Crowley' },
  { full_name: 'Will MacIntosh' },
  { full_name: 'Duncan Corcoran' },
  { full_name: 'Zala Babič' },
  { full_name: 'Benjamin Jackson' },
  { full_name: 'Edward Mullins' },
  { full_name: 'Andrew Tanner' },
  { full_name: 'Andrea Tanner' },
  { full_name: 'Kelin Rapp' },
  { full_name: 'Jennifer Rapp' },
  { full_name: 'Francisco Arias' },
  { full_name: 'Mary Rapp' },
  { full_name: 'Carla Rapp' },
  { full_name: 'Shannon Palmer' },
  { full_name: 'Isabel Pentland' }
]

Guest.create!(guests)

puts "Created #{Guest.count} guests"
